global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "confluent_cloud"
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets: ["api.telemetry.confluent.cloud"]
    scheme: https
    basic_auth:
      username: "LMY4BMZ24ZL7J6MU"
      password: "cflt4EBQjtoq0VrBxRO2uidpAuFkuqkWYqrdgmrqWPjbPmE78I4uLQaF1q7GlJbw"
    metrics_path: /v2/metrics/cloud/export
    params:
      resource_compute_pool_id:
        - "lfcp-pvx0xk"