global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "confluent_cloud"
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets: ["api.telemetry.confluent.cloud"]
    scheme: https
    basic_auth:
      username: "${CCLOUD_API_FLINK}"
      password: "${CCLOUD_API_SECRET_FLINK}"
    metrics_path: /v2/metrics/cloud/export
    params:
      resource_compute_pool_id:
        - "${CCLOUD_COMPUTE_POOL_IDS}"