{
 "title": "Flink Conflunet Cloud",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Statments Status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "confluent_flink_statement_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records In per Job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "confluent_flink_num_records_in", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Records Out per Job",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "confluent_flink_num_records_out",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}