CREATE TABLE market_info_table (
    `MarketInfoId` STRING,
    `AirBags` INT,
    `SunRoof` TINYINT,
    `MagnesiumWheels` TINYINT,
    `ReversSensors` TINYINT,
    `ABS` TINYINT,
    `Hybrid` TINYINT,
    `Doors` TINYINT,
    `EnvironmentFriendlyLevel` INT,
    `SecurityTestLevel` INT,
    `ManufacturerId` INT,
    `ManufacturerText` STRING,
    `ModelId` INT,
    `ModelText` STRING,
    `SubModelId` INT,
    `SubModelText` STRING,
    `FamilyTypeId` INT,
    `FamilyTypeText` STRING,
    `Year` INT,
    `HorsePower` INT,
    `CruseControl` TINYINT,
    `PowerWheel` TINYINT,
    `FullyAutonomic` TINYINT,
    `MarketPrice` INT,
    PRIMARY KEY (`MarketInfoId`) NOT ENFORCED
) WITH (
  'changelog.mode'='upsert',
  'kafka.cleanup-policy'='compact',
  'value.format' = 'avro-registry',
  'scan.startup.mode' = 'earliest-offset'
);